config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :csvs, except: [:edit, :update]
  resources :delivery_notes, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/csv.rb
class Csv < ApplicationRecord
  has_one_attached :csv_file
end

app/models/delivery_note.rb
class DeliveryNote < ApplicationRecord
end

app/models/delivery_note_line.rb
class DeliveryNoteLine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Set the current language
  before_action :set_language

  private

  def set_language
    # Set the language via a query param
    if params[:locale].present? && params[:locale].to_sym.in?(I18n.available_locales)
      session[:locale] = params[:locale]
    end

    # Set the language via an HTTP header
    if session[:locale].blank? && request.env['HTTP_ACCEPT_LANGUAGE']
      session[:locale] = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end

    # If the session locale is valid, use it. Else, use the default locale
    if session[:locale].to_sym.in?(I18n.available_locales)
      I18n.locale = session[:locale]
    else
      session[:locale] = I18n.available_locales.first
    end
  end
end

app/controllers/csvs_controller.rb
class CsvsController < ApplicationController
  before_action :set_csv, only: %i[ show destroy ]

  def index
    @csvs = Csv
    if params[:search].present?
      query = "%#{params[:search]}%"
      @csvs = @csvs.where("name LIKE ?", query)
    end
    @csvs = @csvs.paginate(page: params[:page])
  end

  def new
    @csv = Csv.new
  end

  def create
    @csv = Csv.new(csv_params)

    respond_to do |format|
      if @csv.save
        format.html { redirect_to @csv, notice: "CSV was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @csv.destroy
    respond_to do |format|
      format.html { redirect_to csvs_url, notice: "CSV was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv
      @csv = Csv.find(params[:id])
    end

    def csv_params
      params
        .require(:csv)
        .permit(
          :csv_file
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csvs_helper.rb
module CsvsHelper
end

app/views/csvs/_form.html.erb
<%= form_with(model: @csv) do |form| %>
  <% if @csv.errors.any? %>
    <div class="row">
      <div id="error_explanation" class='p1 bg-info'>
        <h2><%= pluralize(@csv.errors.count, "error") %> prohibited this CSV from being saved:</h2>

        <ul>
          <% @csv.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= render 'form_fields', csv: @csv, form: form %>

  <div class="actions">
    <hr>
    <%= form.submit nil, class: 'btn bg-app b-app' %> or <%= link_to 'cancel', csvs_path %>
  </div>
<% end %>

app/views/csvs/_form_fields.html.erb
  <div class="row">
    CSV file
    <br/>
    <%= form.file_field :csv_file %>
  </div>

app/views/csvs/index.html.erb
<% content_for :title, t('csvs') %>

<h1><%= yield(:title) %></h1>

<div class="row">
  <% if @csvs.blank? %>
  <p>There is no CSV yet</p>
  <% else %>
  <div class='txt-right'>
    <%= form_tag csvs_path, method: :get do %>
      <%= text_field_tag(:search, params[:search], 
                         class: 'card w-100', 
                         autocomplete: 'off', 
                         placeholder: 'Type and press Enter in order to search') %>
    <% end %>
  </div>
  <table>
    <thead>
      <tr>
        <th>Created at</th>
        <th>State</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @csvs.each do |csv| %>
        <tr>
          <td><%= csv.created_at %></td>
          <td><%= highlight(csv.state , params[:search])%></td>
          <td>
            <%= link_to 'Show', csv %>
            <%= link_to 'Destroy', csv_path(csv), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @csvs %>
  <% end %>
</div>

<br/>
<p><%= link_to 'New CSV', new_csv_path, class: 'btn bg-app b-app' %></p>

app/views/csvs/new.html.erb
<% content_for :title, 'New CSV' %>

<h1><%= yield(:title) %></h1>

<%= render 'form', partner: @csv %>

app/views/csvs/show.html.erb
<% content_for :title, @csv.created_at %>

<p><%= link_to 'Back', csvs_path, class: 'styled-link' %> to CSVs</p>

<h1><%= yield(:title) %></h1>

<div class="row">
  <strong>CSV file:</strong>
  <% if @csv.csv_file.attached? %>
    <%= link_to @csv.csv_file.filename, rails_blob_path(@csv.csv_file, disposition: "attachment"), target: '_blank' %>
  <% else %>
    No file attached
  <% end %>
</div>

app/views/layouts/_body_flash.html.erb
<% if !flash[:notice].blank? %>
<div class='row'>
  <p id='notice' class='p1 bg-info notice'><%= notice %></p>
</div>
<% end %>
<% if !flash[:alert].blank? %>
<div class='row'>
  <p id='alert' class='p1 bg-accent alert'><%= alert %></p>
</div>
<% end %>

app/views/layouts/_body_footer.html.erb
<div class='row footer'>
  <%= link_to ENV['COMPANY'], ENV['COMPANY_WEBSITE'], target: '_blank' %> // <%= Time.now.strftime('%Y') %>
</div>

app/views/layouts/_header_css.html.erb
<!-- Be wellcome lit! -->
<%= stylesheet_link_tag '/stylesheets/lit.css' %>
<%= stylesheet_link_tag '/stylesheets/util.css' %>
<!-- Custom style -->
<%= stylesheet_link_tag '/stylesheets/custom.css' %>

app/views/layouts/_navbar_home.html.erb
<a title='Home' href='/' class='ph2 no-link'>
  <img src='/images/app-logo-navbar.png' alt='Pasarela Canteras Aldoyar' class='middle'/>
</a>

app/views/layouts/_navbar_items.html.erb
<%= link_to 'CSVs', csvs_path, class: 'ph2 link' %>
<%= link_to 'Delivery Notes', delivery_notes_path, class: 'ph2 link' %>

app/views/layouts/_navbar_lang_sw.html.erb
<% I18n.available_locales.each do |locale| %>
  <a class='link' href='?locale=<%= locale %>' style="font-weight: <%= locale == I18n.locale ? 'bold' : 'normal' %>">
    <%= t('language', locale: locale) %>
  </a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'/>
    <meta content='2022 - Harroin :: Grupo Microson' name='author'/>
    <meta content='MSP is Management & Signature Prompt' name='description'/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>PCA<%= ('::' + yield(:title) if !yield(:title).blank?).to_s %></title>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= render 'layouts/header_css' %>
  </head>

  <body>
    <div class='c'>
      <div class='bg-app pv2 row'>
        <div class='col'>
          <%= render 'layouts/navbar_home' %>
          <%= render 'layouts/navbar_items' %>
        </div>
        <div class='col txt-right'>
          <%= render 'layouts/navbar_lang_sw' %>
        </div>
      </div>
      <%= render 'layouts/body_flash' %>
      <%= yield %>
      <%= render 'layouts/body_footer' %>
    </div>
  </body>
</html>